import json
import os

notebook_path = "train_board_segmentation_colab-new.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Update Cell 7 (Model definition & loading weights)
cell_7_source = [
    "import torch\n",
    "import torch.nn as nn\n",
    "import torchvision.models.segmentation as segmentation\n",
    "\n",
    "TARGET_WIDTH  = 640\n",
    "TARGET_HEIGHT = 360\n",
    "\n",
    "def get_deeplabv3_model(pretrained=True, num_classes=1, aux_loss=True):\n",
    "    \"\"\"Constructs a DeepLabV3 model with a MobileNetV3-Large backbone adapted for binary mask.\"\"\"\n",
    "    if pretrained:\n",
    "        try:\n",
    "            from torchvision.models.segmentation import DeepLabV3_MobileNet_V3_Large_Weights\n",
    "            weights = DeepLabV3_MobileNet_V3_Large_Weights.DEFAULT\n",
    "            model = segmentation.deeplabv3_mobilenet_v3_large(weights=weights, aux_loss=aux_loss)\n",
    "        except Exception:\n",
    "            model = segmentation.deeplabv3_mobilenet_v3_large(pretrained=True, aux_loss=aux_loss)\n",
    "    else:\n",
    "        model = segmentation.deeplabv3_mobilenet_v3_large(weights=None, aux_loss=aux_loss)\n",
    "        \n",
    "    # Replace classifier head\n",
    "    in_channels = model.classifier[4].in_channels\n",
    "    model.classifier[4] = nn.Conv2d(in_channels, num_classes, kernel_size=1)\n",
    "    \n",
    "    # Replace aux classifier head if present\n",
    "    if aux_loss and model.aux_classifier is not None:\n",
    "        in_channels_aux = model.aux_classifier[4].in_channels\n",
    "        model.aux_classifier[4] = nn.Conv2d(in_channels_aux, num_classes, kernel_size=1)\n",
    "        \n",
    "    return model\n",
    "\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f'Device: {device}')\n",
    "\n",
    "# Initialize DeepLabV3 with pre-trained weights\n",
    "model = get_deeplabv3_model(pretrained=True, num_classes=1, aux_loss=True).to(device)\n",
    "\n",
    "# Load existing weights if present\n",
    "import os\n",
    "import json\n",
    "if os.path.exists('board_segmentation_model.pth'):\n",
    "    try:\n",
    "        architecture = 'deeplabv3'\n",
    "        if os.path.exists('board_segmentation_model_config.json'):\n",
    "            with open('board_segmentation_model_config.json', 'r') as f:\n",
    "                cfg = json.load(f)\n",
    "            architecture = cfg.get('architecture', 'unet')\n",
    "        \n",
    "        if architecture == 'unet':\n",
    "            print('Existing model is UNet. Initializing empty DeepLabV3 for fine-tuning.')\n",
    "        else:\n",
    "            try:\n",
    "                model.load_state_dict(torch.load('board_segmentation_model.pth', map_location=device))\n",
    "                print('Loaded pre-trained DeepLabV3 weights — fine-tuning')\n",
    "            except Exception as e:\n",
    "                print(f'Failed loading with aux_loss=True, trying aux_loss=False: {e}')\n",
    "                model = get_deeplabv3_model(pretrained=False, num_classes=1, aux_loss=False).to(device)\n",
    "                model.load_state_dict(torch.load('board_segmentation_model.pth', map_location=device))\n",
    "                print('Loaded pre-trained DeepLabV3 weights (no aux loss) — fine-tuning')\n",
    "    except Exception as e:\n",
        "        print(f'Could not load existing weights: {e}. Fine-tuning from pre-trained backbone.')\n",
    "else:\n",
    "    print('No local weights found. Fine-tuning from pre-trained torchvision backbone.')\n"
]
nb["cells"][7]["source"] = cell_7_source

# Update Cell 15 (Profiling)
cell_15_source = [
    "import time\n",
    "\n",
    "model.train()\n",
    "dl_times = []\n",
    "fw_times = []\n",
    "bw_times = []\n",
    "\n",
    "print(\"Profiling first 10 batches...\")\n",
    "t0 = time.time()\n",
    "for i, (x_b, y_b) in enumerate(dataloader):\n",
    "    t_dl = time.time() - t0\n",
    "    dl_times.append(t_dl)\n",
    "    \n",
    "    t_start_fw = time.time()\n",
    "    x_b, y_b = x_b.to(device), y_b.to(device)\n",
    "    out_dict = model(x_b)\n",
    "    out = out_dict['out'] if isinstance(out_dict, dict) else out_dict\n",
    "    loss = criterion(out, y_b)\n",
    "    t_fw = time.time() - t_start_fw\n",
    "    fw_times.append(t_fw)\n",
    "    \n",
    "    t_start_bw = time.time()\n",
    "    optimizer.zero_grad()\n",
    "    loss.backward()\n",
    "    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
    "    optimizer.step()\n",
    "    t_bw = time.time() - t_start_bw\n",
    "    bw_times.append(t_bw)\n",
    "    \n",
    "    if i >= 10:\n",
    "        break\n",
    "    t0 = time.time()\n",
    "\n",
    "print(\"\\n--- PROFILING RESULTS ---\")\n",
    "print(f\"Average Dataloader time per batch: {sum(dl_times)/len(dl_times):.4f}s\")\n",
    "print(f\"Average Forward pass time per batch: {sum(fw_times)/len(fw_times):.4f}s\")\n",
    "print(f\"Average Backward pass time per batch: {sum(bw_times)/len(bw_times):.4f}s\")\n",
    "print(f\"Total projected time per epoch: {(sum(dl_times)+sum(fw_times)+sum(bw_times))/len(dl_times) * len(dataloader):.2f}s\")\n"
]
nb["cells"][15]["source"] = cell_15_source

# Update Cell 16 (Dataset, loss function, and main training loop)
cell_16_source = [
    "import torch.optim as optim\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import albumentations as A\n",
    "from albumentations.pytorch import ToTensorV2\n",
    "import cv2\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "\n",
    "EPOCHS         = 100\n",
    "LR             = 1e-4  # Lower learning rate for fine-tuning pre-trained weights\n",
    "AUGMENT_FACTOR = 5\n",
    "BATCH_SIZE     = 8\n",
    "\n",
    "# Ensure GPU/CPU check is explicit\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"Active training device: {device}\")\n",
    "\n",
    "train_transform = A.Compose([\n",
    "    A.HorizontalFlip(p=0.5),\n",
    "    A.Perspective(scale=(0.05, 0.15), keep_size=True, p=0.8),\n",
    "    A.Affine(scale=(0.8, 1.2), translate_percent=(-0.1, 0.1), rotate=(-5, 5), p=0.7),\n",
    "    A.GridDistortion(p=0.4),\n",
    "    A.ColorJitter(brightness=0.4, contrast=0.4, saturation=0.4, hue=0.1, p=0.8),\n",
    "    A.GaussianBlur(blur_limit=(3, 7), p=0.5),\n",
    "    A.GaussNoise(std_range=(0.1, 0.3), p=0.5),\n",
    "    A.CoarseDropout(num_holes_range=(1, 4), hole_height_range=(20, 80), hole_width_range=(20, 80), p=0.6),\n",
    "    A.Normalize(mean=(0,0,0), std=(1,1,1)),\n",
    "    ToTensorV2()\n",
    "])\n",
    "\n",
    "class BoardDataset(Dataset):\n",
    "    def __init__(self, pairs, augment=True, augment_factor=5):\n",
    "        self.augment = augment\n",
    "        self.augment_factor = augment_factor\n",
    "        self.resized_pairs = []\n",
    "        \n",
    "        print(f\"Pre-resizing {len(pairs)} frames to {TARGET_WIDTH}x{TARGET_HEIGHT}...\")\n",
    "        for orig, mask in pairs:\n",
    "            img_rgb = cv2.cvtColor(orig, cv2.COLOR_BGR2RGB)\n",
    "            img_resized = cv2.resize(img_rgb, (TARGET_WIDTH, TARGET_HEIGHT), interpolation=cv2.INTER_AREA)\n",
    "            mask_resized = cv2.resize(mask, (TARGET_WIDTH, TARGET_HEIGHT), interpolation=cv2.INTER_NEAREST)\n",
    "            self.resized_pairs.append((img_resized, mask_resized))\n",
    "        print(\"Pre-resizing completed.\")\n",
    "        \n",
    "    def __len__(self):\n",
    "        if self.augment:\n",
    "            return len(self.resized_pairs) * self.augment_factor\n",
    "        return len(self.resized_pairs)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        real_idx = idx % len(self.resized_pairs)\n",
    "        img, mask = self.resized_pairs[real_idx]\n",
    "        is_base = (idx < len(self.resized_pairs))\n",
    "        \n",
    "        if self.augment and not is_base:\n",
    "            augmented = train_transform(image=img, mask=mask)\n",
    "            x = augmented['image']\n",
    "            y = augmented['mask']\n",
    "        else:\n",
    "            x = torch.from_numpy(img).float().permute(2, 0, 1) / 255.0\n",
    "            y = torch.from_numpy(mask).float()\n",
    "            \n",
    "        y = (y > 0).float().unsqueeze(0)\n",
    "        return x, y\n",
    "\n",
    "dataset    = BoardDataset(pairs, augment=True, augment_factor=AUGMENT_FACTOR)\n",
    "dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)\n",
    "print(f'Dataset: {len(dataset)} samples ({len(pairs)} frames × {AUGMENT_FACTOR})')\n",
    "\n",
    "pos_weight = torch.tensor([3.0]).to(device)\n",
    "\n",
    "class DiceBCELoss(nn.Module):\n",
    "    def __init__(self, pos_weight):\n",
    "        super().__init__()\n",
    "        self.bce = nn.BCEWithLogitsLoss(pos_weight=pos_weight)\n",
    "\n",
    "    def forward(self, inputs, targets, smooth=1):\n",
    "        inputs_sig = torch.sigmoid(inputs)\n",
    "        inputs_flat = inputs_sig.view(-1)\n",
    "        targets_flat = targets.view(-1)\n",
    "        intersection = (inputs_flat * targets_flat).sum()\n",
    "        dice_loss = 1 - (2.*intersection + smooth)/(inputs_flat.sum() + targets_flat.sum() + smooth)\n",
    "        bce_loss = self.bce(inputs, targets)\n",
    "        return bce_loss + dice_loss\n",
    "\n",
    "criterion = DiceBCELoss(pos_weight=pos_weight)\n",
    "optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)\n",
    "scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=LR*0.02)\n",
    "\n",
    "losses = []\n",
    "best_loss = float('inf')\n",
    "\n",
    "import time\n",
    "for epoch in range(1, EPOCHS + 1):\n",
    "    start_time = time.time()\n",
    "    model.train()\n",
    "    ep_loss = 0.0\n",
    "    for x_b, y_b in dataloader:\n",
    "        x_b, y_b = x_b.to(device), y_b.to(device)\n",
    "        optimizer.zero_grad()\n",
    "        \n",
    "        pred_dict = model(x_b)\n",
    "        # DeepLabV3 outputs main and aux logits\n",
    "        loss = criterion(pred_dict['out'], y_b)\n",
    "        if 'aux' in pred_dict and pred_dict['aux'] is not None:\n",
    "            loss += 0.4 * criterion(pred_dict['aux'], y_b)\n",
    "            \n",
    "        loss.backward()\n",
    "        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
    "        optimizer.step()\n",
    "        ep_loss += loss.item()\n",
    "        \n",
    "    scheduler.step()\n",
    "    avg = ep_loss / len(dataloader)\n",
    "    losses.append(avg)\n",
    "    elapsed = time.time() - start_time\n",
    "    \n",
    "    if avg < best_loss:\n",
    "        best_loss = avg\n",
    "        torch.save(model.state_dict(), 'board_segmentation_model.pth')\n",
    "        import json\n",
    "        with open('board_segmentation_model_config.json', 'w') as f:\n",
    "            json.dump({\n",
    "                'in_channels': 3,\n",
    "                'out_channels': 1,\n",
    "                'device': device.type,\n",
    "                'architecture': 'deeplabv3'\n",
    "            }, f)\n",
    "            \n",
    "    print(f'Epoch {epoch:3d}/{EPOCHS} | loss={avg:.4f} | best={best_loss:.4f} | time={elapsed:.2f}s')\n",
    "\n",
    "print(f'\\nTraining complete. Best loss: {best_loss:.4f}')\n"
]
nb["cells"][16]["source"] = cell_16_source

# Update Cell 20 (Validation cell)
cell_20_source = [
    "model.eval()\n",
    "import numpy as np\n",
    "\n",
    "# Compute IoU over ALL pairs without plotting them to avoid crashing Colab\n",
    "print(f\"Calculating IoU over all {len(pairs)} frames...\")\n",
    "ious = []\n",
    "for orig, gt_mask in pairs:\n",
    "    h, w = orig.shape[:2]\n",
    "    if (w, h) != (TARGET_WIDTH, TARGET_HEIGHT):\n",
    "        img = cv2.resize(cv2.cvtColor(orig, cv2.COLOR_BGR2RGB),\n",
    "                          (TARGET_WIDTH, TARGET_HEIGHT), interpolation=cv2.INTER_AREA)\n",
    "    else:\n",
    "        img = cv2.cvtColor(orig, cv2.COLOR_BGR2RGB)\n",
    "        \n",
    "    x = torch.from_numpy(img).float().permute(2,0,1).unsqueeze(0).to(device) / 255.0\n",
    "    with torch.no_grad():\n",
    "        out = model(x)\n",
    "        if isinstance(out, dict):\n",
    "            prob = torch.sigmoid(out['out']).squeeze().cpu().numpy()\n",
    "        else:\n",
    "            prob = out.squeeze().cpu().numpy()\n",
    "        \n",
    "    prob = cv2.resize(prob, (w, h), interpolation=cv2.INTER_LINEAR)\n",
    "    pred_mask = (prob > 0.18).astype(np.uint8) * 255\n",
    "\n",
    "    gt_b   = gt_mask   > 0\n",
    "    pred_b = pred_mask > 0\n",
    "    inter  = (gt_b & pred_b).sum()\n",
    "    union  = (gt_b | pred_b).sum()\n",
    "    iou    = inter / union if union > 0 else 0.0\n",
    "    ious.append(iou)\n",
    "\n",
    "mean_iou = np.mean(ious)\n",
    "print(f\"Mean IoU across all validation frames: {mean_iou:.2%}\")\n",
    "\n",
    "# Select a small sample of 6 frames to visualize safely\n",
    "num_vis = min(6, len(pairs))\n",
    "indices = np.linspace(0, len(pairs) - 1, num_vis, dtype=int)\n",
    "print(f\"Visualizing {num_vis} sample frames...\")\n",
    "\n",
    "fig, axes = plt.subplots(num_vis, 3, figsize=(18, 4 * num_vis))\n",
    "if num_vis == 1: axes = [axes]\n",
    "\n",
    "for plot_idx, idx in enumerate(indices):\n",
    "    orig, gt_mask = pairs[idx]\n",
    "    h, w = orig.shape[:2]\n",
    "    \n",
    "    if (w, h) != (TARGET_WIDTH, TARGET_HEIGHT):\n",
    "        img = cv2.resize(cv2.cvtColor(orig, cv2.COLOR_BGR2RGB),\n",
    "                          (TARGET_WIDTH, TARGET_HEIGHT), interpolation=cv2.INTER_AREA)\n",
    "    else:\n",
    "        img = cv2.cvtColor(orig, cv2.COLOR_BGR2RGB)\n",
    "        \n",
    "    x = torch.from_numpy(img).float().permute(2,0,1).unsqueeze(0).to(device) / 255.0\n",
    "    with torch.no_grad():\n",
    "        out = model(x)\n",
    "        if isinstance(out, dict):\n",
    "            prob = torch.sigmoid(out['out']).squeeze().cpu().numpy()\n",
    "        else:\n",
    "            prob = out.squeeze().cpu().numpy()\n",
    "        \n",
    "    prob = cv2.resize(prob, (w, h), interpolation=cv2.INTER_LINEAR)\n",
    "    pred_mask = (prob > 0.18).astype(np.uint8) * 255\n",
    "    iou = ious[idx]\n",
    "\n",
    "    orig_rgb = cv2.cvtColor(orig, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "    def overlay(base, mask, color):\n",
    "        vis = base.copy()\n",
    "        vis[mask > 0] = (vis[mask > 0] * 0.4 + np.array(color) * 0.6).astype(np.uint8)\n",
    "        return vis\n",
    "\n",
    "    axes[plot_idx][0].imshow(orig_rgb); axes[plot_idx][0].set_title('Original'); axes[plot_idx][0].axis('off')\n",
    "    axes[plot_idx][1].imshow(overlay(orig_rgb, gt_mask,   [0, 200, 0]))\n",
    "    axes[plot_idx][1].set_title('Ground Truth'); axes[plot_idx][1].axis('off')\n",
    "    axes[plot_idx][2].imshow(overlay(orig_rgb, pred_mask, [0, 120, 255]))\n",
    "    axes[plot_idx][2].set_title(f'Predicted  IoU={iou:.2%}'); axes[plot_idx][2].axis('off')\n",
    "\n",
    "plt.suptitle(f'GT (green) vs Predicted (blue) - Mean IoU: {mean_iou:.2%}', fontsize=14)\n",
    "plt.tight_layout(); plt.show()\n"
]
nb["cells"][20]["source"] = cell_20_source

# Update Cell 22 (Download)
cell_22_source = [
    "if IN_COLAB:\n",
    "    from google.colab import files\n",
    "    files.download('board_segmentation_model.pth')\n",
    "    if os.path.exists('board_segmentation_model_config.json'):\n",
    "        files.download('board_segmentation_model_config.json')\n",
    "    print('Downloaded! Replace src/calibration/board_segmentation_model.pth and board_segmentation_model_config.json in your repo.')\n",
    "else:\n",
    "    import shutil\n",
    "    shutil.copy('board_segmentation_model.pth', 'src/calibration/board_segmentation_model.pth')\n",
    "    if os.path.exists('board_segmentation_model_config.json'):\n",
    "        shutil.copy('board_segmentation_model_config.json', 'src/calibration/board_segmentation_model_config.json')\n",
    "    print('Saved model and configuration locally.')\n"
]
nb["cells"][22]["source"] = cell_22_source

# Write back the notebook
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Notebook train_board_segmentation_colab-new.ipynb successfully updated for DeepLabV3!")
